import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full" dir="rtl">
      <body className={`font-IRANSansX h-full flex justify-center w-full `}>
        <div className="w-full h-full flex flex-col justify-center items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
